apiVersion: v1
kind: ConfigMap
metadata:
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" .Values "serviceName" "etc" ) }}
  labels:
    app.kubernetes.io/component: "config"
data:
  {{- range $filename, $content := .Files.Glob "submodule_config/*.yml" }}
  {{ $filename | trimPrefix "submodule_config/" }}: |-
    {{- $content | toString | nindent 4 }}
  {{- end -}}
