volumes: &volumes
  vol-etc-gscloud:
    configMap:
      name: gs-cloud-datadir-etc

additional-stuff: &additional-stuff
  volumes: *volumes

geoservercloud:
  geoserver:
    services:
      gateway: *additional-stuff
      webui: *additional-stuff
      rest: *additional-stuff
      wms: *additional-stuff
      wcs: *additional-stuff
      wfs: *additional-stuff
      gwc: *additional-stuff

nfsserver: 'not-set'
nfs:
  raster:
    pvcname: gs-cloud-raster-nfs-claim
    pvname: gs-cloud-raster-nfs
    path: /nfs/raster
    storage: 10Gi
  config:
    pvcname: gs-cloud-datadir-nfs-claim
    pvname: gs-cloud-datadir-nfs
    path: /nfs/datadir
    storage: 10Gi
  cache:
    pvcname: gs-cloud-gwc-cache-nfs-claim
    pvname: gs-cloud-gwc-cache-nfs
    path: /nfs/tiles
    storage: 10Gi

rabbitmq:
  enabled: true
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 0.1
      memory: 512Mi

  image:
    registry: docker.io
    repository: bitnami/rabbitmq
    tag: 3.9.13-debian-10-r14
  auth:
    username: geoserver
  persistence:
    enabled: false
